### PR TITLE
Assignment 1

### PR DESCRIPTION
**Pull request by sharadbrat**
120258
120542

### CODE REVIEW

**Comment by volzotan** [comment]
everything looks fine, except your error handling could be improved a bit (-0.5). Total points: 4.5/5

**Comment by sharadbrat** [comment]
> everything looks fine, except your error handling could be improved a bit (-0.5). Total points: 4.5/5

Disagree, according to our assignment sheet we added proper exception handling for all the mentioned in assignment sheet exceptions. If there were additional requirements for that, they should be explicitly put in the assignment sheet. Either I have not found strict requirements in the assignment sheet, either there are no strict requirements at all.

**Comment by volzotan** [comment]
What I want you to learn is to handle Exceptions explicitly and check for special cases. What you did in your submission is simply printing the class name of the Exception object ( error.getClass().toString(); ). You did not adress certain types of Exceptions separately, you did not check user input. What happens if Androids TextEdit Widget is empty when .getText is called?
Usually I'm less strict but the very first exercise is quite simple so a submission should be flawless for full points.

Did that answer your question? If you want to discuss this further just see me after the exercise session on friday.

**Comment by sharadbrat** [comment]
Firstly, there were no explicit requirements for exception handling of all the types of exceptions, that could possibly appear.

> What you did in your submission is simply printing the class name of the Exception object ( error.getClass().toString(); )

Secondly, this is not the only thing we do, we also print out the message of error, if it presents.

If github discussion is not the best place to discuss the assignment, the int would be better to discuss it after the exercise session :)

**Pull request closed without merging**
